default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= ENV['DATABASE_NAME'] %>
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>
  port: <%= ENV['DATABASE_PORT'] %>

test:
  <<: *default
  database: workout_tracker_test

production:
  <<: *default
  database: workout_tracker_production
  username: workout_tracker
  password: <%= ENV['YOUR_APP_NAME_DATABASE_PASSWORD'] %>